package meta

const (
	MSK_MAGIC_VALUE  = "MSK"
	MSK_FILE_VERSION = byte(1)

	MSK_MAGIC_SIZE   = 3
	MSK_VERSION_SIZE = 1
	MSK_SALT_SIZE    = 16
	MSK_NONCE_SIZE   = 12
	MSK_HEADER_SIZE  = MSK_MAGIC_SIZE + MSK_VERSION_SIZE + MSK_SALT_SIZE + MSK_NONCE_SIZE
)

const (
	SECRET_NAME_LENGTH_SIZE     = 2
	SECRET_PASSWORD_LENGTH_SIZE = 2
)
