package vault

import "time"

const (
	SESSION_NONCE_SIZE  = 12
	SESSION_EXPIRY_SIZE = 8
	SESSION_HEADER_SIZE = SESSION_NONCE_SIZE + SESSION_EXPIRY_SIZE
	SESSION_TTL         = 15 * time.Minute
	SESSION_TOKEN_SIZE  = 32
)
