package cli

import (
	fl "github.com/amauribechtoldjr/msk/internal/file_manager"
	u "github.com/amauribechtoldjr/msk/utils"
	"github.com/spf13/cobra"
)

var c = u.Check

var configCmd = &cobra.Command{
	Use:   "config",
	Aliases: []string{"c"},
	Short: "Used to config the master key",
	Long: ``,
	Run: config,
}

type Users struct {
	Name  string `csv:"name"`
	Age int `csv:"age"`
}

func config(cmd *cobra.Command, args []string) {
	masterKey, _ := cmd.Flags().GetBytesHex("manual")
	// isAutoGenerated, _ := cmd.Flags().GetBool("auto")


	fl.InitMSKConfig(masterKey)
}

func init() {
	rootCmd.AddCommand(configCmd)

	configCmd.Flags().BytesHexP("manual", "m", nil, "Set the master key manually.")
	configCmd.Flags().BoolP("auto", "a", false, "Create and set the master key.")
}
