package cli

import (
	"fmt"

	fl "github.com/amauribechtoldjr/msk/internal/file_manager"

	"github.com/spf13/cobra"
)

var configCmd = &cobra.Command{
	Use:   "config",
	Aliases: []string{"c"},
	Short: "Used to config the master key",
	Long: ``,
	Run: config,
}

type Users struct {
	Name  string `csv:"name"`
	Age int `csv:"age"`
}

func config(cmd *cobra.Command, args []string) {
	// masterKey, _ := cmd.Flags().GetString("manual")
	// isAutoGenerated, _ := cmd.Flags().GetBool("auto")
	
	// fl.Read()

	result, err := fl.ReadCSV[Users]("./examples/test.csv")

	if err != nil {
		fmt.Println(err)
	}

	for i, value := range result {
		fmt.Println(i)
		fmt.Println(value.Age)
	}
}

func init() {
	rootCmd.AddCommand(configCmd)

	configCmd.Flags().StringP("manual", "m", "", "Set the master key manually.")
	configCmd.Flags().BoolP("auto", "a", false, "Create and set the master key.")
}
